### PR TITLE
Fix Eclipse project setup

### PR DESCRIPTION
**Pull request by planger**
These are the changes required (at least for me) to make the projects build in Eclipse. Am I the only one having these issues? Thanks!

### CODE REVIEW

**Comment by tortmayr** [comment]
For me these issues are fixed with https://github.com/eclipse-glsp/glsp-server/pull/30.
Did you check if you still have these issues on the latest master?
Also we cannot use Java11 in the project settings (because a certain customer project requires Java 10)

**Comment by planger** [comment]
> For me these issues are fixed with #30.
> Did you check if you still have these issues on the latest master?

Yes, I did. I even tried to import the clean master in a fresh workspace, with no avail. :/ I still got several type mismatch errors.

**Comment by planger** [comment]
Just for the record, these are the errors I get on master with an Eclipse 2019-12 and OpenJDK 11 installed.
```
The constructor Server(InetSocketAddress) is undefined	WebsocketServerLauncher.java	/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket	line 61	Java Problem
The type String is not visible	CreateConnectionOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 52	Java Problem
The type String is not visible	CreateNodeOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 46	Java Problem
The type String is not visible	GModelUtil.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/util	line 40	Java Problem
The type String is not visible	RequestOperationsActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 62	Java Problem
The type String is not visible	RequestTypeHintsActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 63	Java Problem
Type mismatch: cannot convert from Optional<Action> to Optional<Action>	ExecuteServerCommandActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 43	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	ApplyLabelEditOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 38	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	CreateConnectionOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 65	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	CreateConnectionOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 66	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	CreateNodeOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 61	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	DeleteOperationHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler	line 70	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	RequestMarkersHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 50	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	RequestPopupModelActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 42	Java Problem
Type mismatch: cannot convert from Optional<GModelElement> to Optional<GModelElement>	ValidateLabelEditActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 43	Java Problem
Type mismatch: cannot convert from Optional<Object> to Optional<Action>	RequestPopupModelActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 44	Java Problem
Type mismatch: cannot convert from Optional<String> to Optional<String>	RequestOperationsActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 65	Java Problem
Type mismatch: cannot convert from Optional<String> to Optional<String>	RequestTypeHintsActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 66	Java Problem
Type mismatch: cannot convert from Optional<String> to Optional<String>	SaveModelActionHandler.java	/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler	line 71	Java Problem
```

Thanks a lot for any insight!

**Comment by tortmayr** [comment]
I have set the plugin compliance to Java 1.8. This workaround resolves the weird Eclipse-related issues and Java10 compatibility is maintained.

**Comment by planger** [comment]
Great, thanks @tortmayr! That works now for me too.

**Pull request merged**
